version: '3.3'

volumes:
  static:
  media:
  pg_data_prod:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_prod:/var/lib/postgresql/data

  backend:
    image: bynin/foodgram_backend
    env_file: .env

    volumes:
      - static:/backend_static/static
      - media:/app/media

    depends_on:
      - db

  frontend:
    image: bynin/foodgram_frontend
    env_file: .env
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    env_file: .env

    ports:
      - "8000:80"
    volumes:

      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/

      - static:/var/html/static/
      - media:/var/html/media/
